const ERROR_VALIDATION = 400;
const ERROR_AUTH = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_DEFAULT = 500;

module.exports = {
  ERROR_VALIDATION,
  ERROR_AUTH,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_CONFLICT,
  ERROR_DEFAULT,
};
